# Simple workflow for deploying static content to GitHub Pages
name: Deploy React to GitHub Pages

uses: bitovi/github-actions-react-to-github-pages@v1.2.1
  with:
    # Specifies if this action should checkout the code
    checkout: # optional, default is true
    # Specifies the path of the static assets after building
    path: # optional, default is dist
    # Specifies the command to run the installation.
    install_command: # optional, default is npm ci
    # Specifies the command to run after the install command for the build
    build_command: # optional, default is npm run build
